export const ISABELA_CITY_BARANGAYS = [
  "Aguada",
  "Balatanay",
  "Baluno",
  "Begang",
  "Binuangan",
  "Busay",
  "Cabunbata",
  "Cawa-Cawa",
  "Communal",
  "Isabela East Port (Poblacion)",
  "Isabela West Port (Poblacion)",
  "Kapatagan Grande",
  "Kaumpurnah Zone I",
  "Kaumpurnah Zone II",
  "Kaumpurnah Zone III",
  "Kapayawan",
  "Laisan",
  "Limpapa",
  "Lugbung",
  "Lukbuton",
  "Lumbang",
  "Makiri",
  "Malim",
  "Marang-Marang",
  "Matarling",
  "Matatag",
  "Menzi",
  "Malamawi",
  "Panunsulan",
  "Port Area",
  "Riverside",
  "San Rafael",
  "Santa Clara",
  "Santa Cruz",
  "Seaside",
  "Small Kapatagan",
  "Sumagdang",
  "Sungkayut",
  "Tabuk",
  "Tampalan",
  "Tebiah",
  "Tunghatang",
  "Unsang",
  "Upper Hingabu",
  "Upper Port Area",
];

export const WESTERN_MINDANAO_TRIBES = [
  "Subanen / Subanon",
  "Yakan",
  "Sama / Samal",
  "Sama Badjao / Bajau",
  "Sama Bangingi",
  "Tausug",
  "Maranao",
  "Maguindanaon",
  "Kalibugan / Kolibugan",
  "Iranun",
  "Visayan / Bisaya",
  "Chavacano",
  "Tagalog",
  "Other / Non-IP",
];

export const WESTERN_MINDANAO_RELIGIONS = [
  "Islam",
  "Roman Catholic",
  "Evangelical / Protestant",
  "Seventh-day Adventist",
  "Iglesia ni Cristo",
  "Jehovah's Witnesses",
  "Bible Baptist Church",
  "United Church of Christ in the Philippines (UCCP)",
  "Church of Jesus Christ of Latter-day Saints (Mormon)",
  "Other Religion",
];

export const optionsWithCurrentValue = (options, currentValue) => {
  const value = String(currentValue || "").trim();
  return value && !options.some((option) => option.toLowerCase() === value.toLowerCase())
    ? [value, ...options]
    : options;
};
