export const ISABELA_CITY_BARANGAYS = [
  "Aguada",
  "Balatanay",
  "Baluno",
  "Begang",
  "Binuangan",
  "Busay",
  "Cabunbata",
  "Calvario",
  "Carbon",
  "Diki",
  "Isabela Eastside",
  "Isabela Proper",
  "Dona Ramona T. Alano",
  "Kapatagan Grande",
  "Kaumpurnah Zone I",
  "Kaumpurnah Zone II",
  "Kaumpurnah Zone III",
  "Kumalarang",
  "La Piedad",
  "Lampinigan",
  "Lanote",
  "Lukbuton",
  "Lumbang",
  "Makiri",
  "Maligue",
  "Marang-marang",
  "Marketsite",
  "Menzi",
  "Panigayan",
  "Panunsulan",
  "Port Area",
  "Riverside",
  "San Rafael",
  "Santa Barbara",
  "Santa Cruz",
  "Seaside",
  "Sumagdang",
  "Sunrise Village",
  "Tabiawan",
  "Tabuk",
  "Timpul",
  "Kapayawan",
  "Masula",
  "Small Kapatagan",
  "Tampalan",
];

export const WESTERN_MINDANAO_TRIBES = [
  "Subanen / Subanon",
  "Yakan",
  "Sama / Samal",
  "Sama Badjao / Bajau",
  "Sama Bangingi",
  "Tausug",
  "Maranao",
  "Maguindanaon",
  "Kalibugan / Kolibugan",
  "Iranun",
  "Visayan / Bisaya",
  "Chavacano",
  "Tagalog",
  "Other / Non-IP",
];

export const WESTERN_MINDANAO_RELIGIONS = [
  "Islam",
  "Roman Catholic",
  "Evangelical / Protestant",
  "Seventh-day Adventist",
  "Iglesia ni Cristo",
  "Jehovah's Witnesses",
  "Bible Baptist Church",
  "United Church of Christ in the Philippines (UCCP)",
  "Church of Jesus Christ of Latter-day Saints (Mormon)",
  "Other Religion",
];

export const optionsWithCurrentValue = (options, currentValue) => {
  const value = String(currentValue || "").trim();
  return value && !options.some((option) => option.toLowerCase() === value.toLowerCase())
    ? [value, ...options]
    : options;
};
