-- TARGET: shared IECES Supabase only.
-- Creates the remaining BMI tables alongside the unified students table.
begin;
create table if not exists public.schools (
  school_id text primary key,
  name text not null,
  district text,
  address text,
  logo_url text,
  created_at timestamptz not null default now()
);
create table if not exists public.bmi_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null unique,
  lastname text not null,
  firstname text not null,
  middleinitial text,
  fullname text not null,
  role text not null check (role in ('school', 'division')),
  position text not null,
  created_at timestamptz not null default now(),
  school_id text references public.schools(school_id) on update cascade,
  school_name text
);
create table if not exists public.sbfp_config (
  id text primary key,
  config jsonb not null default '{}'::jsonb,
  grades text[] not null default '{}'::text[],
  criteria text[] not null default '{}'::text[],
  criteriongraderestrictions jsonb not null default '{}'::jsonb,
  set_by text,
  set_at timestamptz default timezone('utc'::text, now()),
  "setBy" text,
  "setAt" timestamptz default timezone('utc'::text, now())
);
create table if not exists public.sbfp_enrolment (
  id bigint generated by default as identity primary key,
  school_id varchar not null references public.schools(school_id) on update cascade,
  sy varchar not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  total bigint default 0,
  unique (school_id, sy)
);
alter table public.schools enable row level security;
alter table public.bmi_profiles enable row level security;
alter table public.sbfp_config enable row level security;
alter table public.sbfp_enrolment enable row level security;
create or replace function public.is_bmi_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    exists (select 1 from public.admin_users a where a.user_id = auth.uid())
    or exists (
      select 1 from public.bmi_profiles p
      where p.id = auth.uid() and p.role = 'division'
    );
$$;
create or replace function public.current_bmi_school_id()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.school_id from public.bmi_profiles p where p.id = auth.uid();
$$;
revoke all on function public.is_bmi_manager() from public, anon;
revoke all on function public.current_bmi_school_id() from public, anon;
grant execute on function public.is_bmi_manager() to authenticated;
grant execute on function public.current_bmi_school_id() to authenticated;
drop policy if exists "BMI users can read schools" on public.schools;
create policy "BMI users can read schools" on public.schools
for select to authenticated using (true);
drop policy if exists "BMI users can create schools" on public.schools;
create policy "BMI users can create schools" on public.schools
for insert to authenticated with check (true);
drop policy if exists "BMI users can update permitted schools" on public.schools;
create policy "BMI users can update permitted schools" on public.schools
for update to authenticated
using (public.is_bmi_manager() or school_id = public.current_bmi_school_id())
with check (public.is_bmi_manager() or school_id = public.current_bmi_school_id());
drop policy if exists "BMI users can read permitted profiles" on public.bmi_profiles;
create policy "BMI users can read permitted profiles" on public.bmi_profiles
for select to authenticated
using (id = auth.uid() or public.is_bmi_manager());
drop policy if exists "BMI users can create own profile" on public.bmi_profiles;
create policy "BMI users can create own profile" on public.bmi_profiles
for insert to authenticated with check (id = auth.uid());
drop policy if exists "BMI users can update permitted profiles" on public.bmi_profiles;
create policy "BMI users can update permitted profiles" on public.bmi_profiles
for update to authenticated
using (id = auth.uid() or public.is_bmi_manager())
with check (id = auth.uid() or public.is_bmi_manager());
drop policy if exists "BMI admins can delete profiles" on public.bmi_profiles;
create policy "BMI admins can delete profiles" on public.bmi_profiles
for delete to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));
drop policy if exists "BMI users can read configuration" on public.sbfp_config;
create policy "BMI users can read configuration" on public.sbfp_config
for select to authenticated using (true);
drop policy if exists "BMI managers can create configuration" on public.sbfp_config;
create policy "BMI managers can create configuration" on public.sbfp_config
for insert to authenticated with check (public.is_bmi_manager());
drop policy if exists "BMI managers can update configuration" on public.sbfp_config;
create policy "BMI managers can update configuration" on public.sbfp_config
for update to authenticated using (public.is_bmi_manager())
with check (public.is_bmi_manager());
drop policy if exists "BMI users can read permitted enrolment" on public.sbfp_enrolment;
create policy "BMI users can read permitted enrolment" on public.sbfp_enrolment
for select to authenticated
using (public.is_bmi_manager() or school_id = public.current_bmi_school_id());
drop policy if exists "BMI users can create permitted enrolment" on public.sbfp_enrolment;
create policy "BMI users can create permitted enrolment" on public.sbfp_enrolment
for insert to authenticated
with check (public.is_bmi_manager() or school_id = public.current_bmi_school_id());
drop policy if exists "BMI users can update permitted enrolment" on public.sbfp_enrolment;
create policy "BMI users can update permitted enrolment" on public.sbfp_enrolment
for update to authenticated
using (public.is_bmi_manager() or school_id = public.current_bmi_school_id())
with check (public.is_bmi_manager() or school_id = public.current_bmi_school_id());
-- School users see and modify their own students; division/admin users can
-- manage the full shared registry. Existing IECES policies remain intact.
drop policy if exists "BMI users can read permitted students" on public.students;
create policy "BMI users can read permitted students" on public.students
for select to authenticated
using (public.is_bmi_manager() or school_id = public.current_bmi_school_id());
drop policy if exists "BMI users can create permitted students" on public.students;
create policy "BMI users can create permitted students" on public.students
for insert to authenticated
with check (public.is_bmi_manager() or school_id = public.current_bmi_school_id());
drop policy if exists "BMI users can update permitted students" on public.students;
create policy "BMI users can update permitted students" on public.students
for update to authenticated
using (public.is_bmi_manager() or school_id = public.current_bmi_school_id())
with check (public.is_bmi_manager() or school_id = public.current_bmi_school_id());
drop policy if exists "BMI users can delete permitted students" on public.students;
create policy "BMI users can delete permitted students" on public.students
for delete to authenticated
using (public.is_bmi_manager() or school_id = public.current_bmi_school_id());
grant select, insert, update on public.schools to authenticated;
grant select, insert, update, delete on public.bmi_profiles to authenticated;
grant select, insert, update on public.sbfp_config to authenticated;
grant select, insert, update on public.sbfp_enrolment to authenticated;
grant usage, select on all sequences in schema public to authenticated;
commit;
